from pptx import Presentation

def generate_ppt_report(
    company,
    summary,
    risk,
    investment,
    strategy,
    output_path="financial_presentation.pptx"
):

    prs = Presentation()

    # ============================================
    # TITLE SLIDE
    # ============================================

    slide_layout = prs.slide_layouts[0]

    slide = prs.slides.add_slide(slide_layout)

    slide.shapes.title.text = (
        f"{company} Financial AI Report"
    )

    slide.placeholders[1].text = (
        "Generated by FinSight AI"
    )

    # ============================================
    # EXECUTIVE SUMMARY
    # ============================================

    slide_layout = prs.slide_layouts[1]

    slide = prs.slides.add_slide(slide_layout)

    slide.shapes.title.text = (
        "Executive Summary"
    )

    slide.placeholders[1].text = summary

    # ============================================
    # RISK ANALYSIS
    # ============================================

    slide = prs.slides.add_slide(slide_layout)

    slide.shapes.title.text = (
        "Risk Analysis"
    )

    slide.placeholders[1].text = risk

    # ============================================
    # INVESTMENT INSIGHTS
    # ============================================

    slide = prs.slides.add_slide(slide_layout)

    slide.shapes.title.text = (
        "Investment Insights"
    )

    slide.placeholders[1].text = investment

    # ============================================
    # STRATEGY RECOMMENDATIONS
    # ============================================

    slide = prs.slides.add_slide(slide_layout)

    slide.shapes.title.text = (
        "Future Strategy"
    )

    slide.placeholders[1].text = strategy

    # ============================================
    # SAVE PPT
    # ============================================

    prs.save(output_path)

    return output_path